package com.girisk.sports.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.girisk.common.exception.BusinessException;
import com.girisk.config.DemoBootstrapProperties;
import com.girisk.sports.repository.SportsMatchRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.core.io.ClassPathResource;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;

import java.io.InputStream;
import java.time.Duration;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Loads classpath Germany demo assets into Redis fixture views + sports_match / ExposureStore.
 * Does not depend on girisk-engine; assets are generated by LocalExposureReplayMain --skip-redis.
 */
@Service
public class ExposureDemoBootstrapService {

    private static final Logger log = LoggerFactory.getLogger(ExposureDemoBootstrapService.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final Duration VIEW_TTL = Duration.ofDays(7);

    private final DemoBootstrapProperties props;
    private final SportsReplaySeedService replaySeedService;
    private final SportsMatchRepository matchRepository;
    private final StringRedisTemplate redis;

    public ExposureDemoBootstrapService(
            DemoBootstrapProperties props,
            SportsReplaySeedService replaySeedService,
            SportsMatchRepository matchRepository,
            ObjectProvider<StringRedisTemplate> redis) {
        this.props = props;
        this.replaySeedService = replaySeedService;
        this.matchRepository = matchRepository;
        this.redis = redis.getIfAvailable();
    }

    public boolean isRedisAvailable() {
        return redis != null;
    }

    /**
     * Idempotent bootstrap for exposure-demo:
     * Redis top empty → full load; Redis present but H2 match missing → force re-seed
     * (H2 is in-memory and clears on restart while Redis may retain views).
     */
    public Map<String, Object> ensureDemoLoaded() {
        if (redis == null) {
            throw new BusinessException("Redis 未启用，无法灌入演示物化视图");
        }
        String matchCode = peekDemoMatchCode();
        Long size = redis.opsForZSet().zCard("girisk:view:top:worstloss");
        boolean redisReady = size != null && size > 0;
        boolean matchReady = matchCode != null && matchRepository.findByCode(matchCode).isPresent();
        if (redisReady && matchReady) {
            return Map.of("loaded", false, "reason", "already_present", "topCount", size, "matchCode", matchCode);
        }
        // Redis may survive restart while H2 does not — always re-seed sports store if needed.
        return loadDemo(true);
    }

    private String peekDemoMatchCode() {
        try {
            String prefix = classpathPrefix();
            JsonNode seed = readJson(prefix + "/sports-seed.json");
            return text(seed, "matchCode", "germany-paraguay");
        } catch (Exception e) {
            return "germany-paraguay";
        }
    }

    private String classpathPrefix() {
        String prefix = props.getClasspathPrefix();
        if (prefix == null || prefix.isBlank()) {
            prefix = "demo/germany-paraguay";
        }
        if (prefix.endsWith("/")) {
            prefix = prefix.substring(0, prefix.length() - 1);
        }
        return prefix;
    }

    /**
     * @param force when true, overwrite Redis fixture view + re-seed sports store even if data exists
     */
    public Map<String, Object> loadDemo(boolean force) {
        if (redis == null) {
            throw new BusinessException("Redis 未启用，无法灌入演示物化视图");
        }
        String prefix = classpathPrefix();

        try {
            JsonNode viewDoc = readJson(prefix + "/fixture-view.json");
            SportsReplaySeedService.ReplaySeedRequest seedReq = MAPPER.treeToValue(
                    readJson(prefix + "/sports-seed.json"),
                    SportsReplaySeedService.ReplaySeedRequest.class);

            String fixtureId = text(viewDoc, "fixtureId", seedReq.matchCode());
            long worstLossCents = viewDoc.path("worstLossCents").asLong(0);
            JsonNode hashNode = viewDoc.path("hash");
            if (!hashNode.isObject()) {
                throw new BusinessException("fixture-view.json 缺少 hash");
            }

            if (!force) {
                Long size = redis.opsForZSet().zCard("girisk:view:top:worstloss");
                boolean matchReady = matchRepository.findByCode(fixtureId).isPresent();
                if (size != null && size > 0 && matchReady) {
                    return Map.of(
                            "loaded", false,
                            "reason", "already_present",
                            "topCount", size,
                            "matchCode", fixtureId);
                }
            }

            Map<String, String> hash = new LinkedHashMap<>();
            Iterator<Map.Entry<String, JsonNode>> it = hashNode.fields();
            while (it.hasNext()) {
                Map.Entry<String, JsonNode> e = it.next();
                hash.put(e.getKey(), e.getValue().isValueNode() ? e.getValue().asText() : e.getValue().toString());
            }
            hash.put("updatedAt", String.valueOf(System.currentTimeMillis()));

            String key = "girisk:view:fixture:" + fixtureId;
            redis.opsForHash().putAll(key, hash);
            redis.expire(key, VIEW_TTL);
            redis.opsForZSet().add("girisk:view:top:worstloss", fixtureId, worstLossCents);

            Map<String, Object> seedResult = replaySeedService.seed(seedReq);
            log.info("Exposure demo loaded fixtureId={} force={}", fixtureId, force);

            Map<String, Object> out = new LinkedHashMap<>();
            out.put("loaded", true);
            out.put("force", force);
            out.put("fixtureId", fixtureId);
            out.put("worstLossCents", worstLossCents);
            out.put("seed", seedResult);
            return out;
        } catch (BusinessException e) {
            throw e;
        } catch (Exception e) {
            throw new BusinessException("灌入演示数据失败: " + e.getMessage());
        }
    }

    private static JsonNode readJson(String classpath) throws Exception {
        ClassPathResource res = new ClassPathResource(classpath);
        if (!res.exists()) {
            throw new BusinessException("缺少 classpath 资源: " + classpath);
        }
        try (InputStream in = res.getInputStream()) {
            return MAPPER.readTree(in);
        }
    }

    private static String text(JsonNode n, String field, String fallback) {
        JsonNode v = n.get(field);
        if (v == null || v.isNull() || v.asText().isBlank()) {
            return fallback;
        }
        return v.asText();
    }
}
